accounting/urls.py
from django.urls import path
from . import view1
from . import view

app_name='accounting'

urlpatterns = [
    path('',view.all_cashbox,name='all_cashbox'),
    path('add_cashbox',view.add_cashbox,name='add_cashbox'),
    path('edit_cashbox/<int:id>',view1.edit_cashbox,name='edit_cashbox'),

    path('active',view.active_cashbox,name='active'),
    path('deactive',view.deactive,name='deactive'),

    path('mytrannsaction/<int:id>',view.transaction,name='transaction'),
    path('add_inbox',view.add_inbox,name='add_inbox'),
    path('add_absentminded',view.add_absentminded,name='add_absentminded'),

   
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from dashboard.views import index




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index),
    path('dashboard/',include('dashboard.urls')),
    path('authuser/',include('authuser.urls'),),
    
    path('tinder/',include('tinder.urls')),

    path('accounting/',include('accounting.urls')),
    path('myproject/',include('myproject.urls')),

    path('inventory/',include('inventory.urls')),
   
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tinder/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name='tinder'

urlpatterns = [

    path('all_tinder',login_required(views.all_tinder),name='all_tinder'),
    path('delete_tinder',login_required(views.delete_tinder),name='delete_tinder'),
    path('edit_tinder/<int:id>',login_required(views.edit_tinder),name='edit_tinder'),
    path('detail_tinder/<int:id>',login_required(views.detail_tinder),name='detail_tinder'),
    path('add_tinder',login_required(views.add_tinder),name='add_tinder'),
    path('save_tinder',login_required(views.save_tinder),name='save_tinder'),

    path('edit_tinder_file',login_required(views.edit_tinder_file),name='edit_tinder_file'),
    path('delete_file/<int:id>',login_required(views.delete_file),name='delete_file'),

    path('edit_item',login_required(views.edit_item),name='edit_item'),
    path('delete_item',login_required(views.delete_item),name='delete_item'),
]

accounting/models.py
from django.db import models
from authuser.models import User


CASHBOX_TYPE=[
    ('CASH','نقدي'),
    ('CHEQUE','شيكات'),
]
# انشاء الخزينة بصفة عامة سواء نقدى أو شيكات
class CashBox(models.Model):        # الخزينة
    name=models.CharField(max_length=120)
    type=models.CharField(max_length=75,choices=CASHBOX_TYPE)
    is_main=models.BooleanField(default=False)
    is_active=models.BooleanField(default=True)
    treasurer=models.ForeignKey(User,related_name='cash_treasurer',on_delete=models.SET_NULL,null=True,blank=True)  # أمين الخزينة
    details=models.TextField(max_length=1500)

    created_at=models.DateTimeField(auto_now_add=True)
    edit_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
    
# انش اء حركة الخزينة  من وراد ومنصرف للخزينة دى
class CashTransaction(models.Model):        # حركة الخزينة
    cashbox=models.ForeignKey(CashBox,related_name='transaction_cashbox',on_delete=models.CASCADE)        # أسم الخزينة
    date_transaction=models.DateField()           # تاريخ الحركة
    no=models.IntegerField()                          # رقم الايصال
    category=models.ForeignKey('Category',related_name='transaction_category',on_delete=models.SET_NULL,null=True,blank=True)
    inbox=models.FloatField(null=True,blank=True)       # الوارد
    absentminded=models.FloatField(null=True,blank=True)  # المنصرف
    details=models.TextField(max_length=1500,null=True,blank=True)

    def __str__(self):
        return str(self.category)
    

CATEGORY_TYPE=[
    ('IN','IN'),
    ('OUT','OUT'),
] 
# انشاء التصنيف لحركة الخزين  سواء كان م.إدارية  أو مصاريف تشغيل فى حالة الصرف  لو فى حالة التوريد فى مسمسات أخرى
class Category(models.Model):            # التصنيف
    name=models.CharField(max_length=120)
    type=models.CharField(max_length=120,choices=CATEGORY_TYPE)

    def __str__(self):
        return self.name

accounting/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .models import CashBox,CashTransaction
from authuser.models import User
from django.http import HttpResponseRedirect
from django.contrib import messages
from . import models



@login_required
def all_cashbox(request):
    all_cashbox=CashBox.objects.all()
    context={
        'all_cashbox':all_cashbox
    }
    return render(request,'accounting/all_cashbox.html',context)

@login_required
def add_cashbox(request):
    users=User.objects.all()
    if request.method =='POST':
        name=request.POST.get('name')
        type=request.POST.get('type')
        is_main=True if request.POST.get('is_main') == 'on' else False
        is_active=True if request.POST.get('is_active') == 'on' else False
        treasurer_id=request.POST.get('treasurer')
        details=request.POST.get('details')

        CashBox.objects.create(
            name=name,
            type=type,
            is_main=is_main,
            is_active=is_active,
            treasurer_id=treasurer_id,
            details=details
        )
        messages.success(request,'مبرروك تم الحفظ بنجاح تحياتى')
        return redirect('accounting:all_cashbox')

    context={
        'users':users
    }
    return render(request,'accounting/add_cashbox.html',context)


@login_required
def edit_cashbox(request,id):
    cashbox=CashBox.objects.get(id=id)
    users=User.objects.all()
    if request.method == 'POST':
        name=request.POST.get('name')
        type=request.POST.get('type')
        is_main=True if request.POST.get('is_main') == 'on' else False
        is_active=True if request.POST.get('is_active') == 'on' else False
        treasurer_id=request.POST.get('treasurer')
        details=request.POST.get('details')

        cashbox.name=name
        cashbox.type=type
        cashbox.is_active=is_active
        cashbox.is_main=is_main
        cashbox.treasurer_id=treasurer_id
        cashbox.details=details
        cashbox.save()

        return redirect('accounting:all_cashbox')


    context={
        'cashbox':cashbox,
        'users':users
    }


    return render(request,'accounting/edit_cashbox.html',context)

@login_required
def active_cashbox(request):
    
    if request.method == 'POST':
        cashbox_id=request.POST.get('id')
        cashbox=CashBox.objects.get(id=cashbox_id)
        cashbox.is_active=True 
        cashbox.save()
        messages.success(request,'تم   التنشيط بنجاح ')

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def deactive(request):
    if request.method =='POST':
        cashbox_id=request.POST.get('id')
        cashbox=CashBox.objects.get(id=cashbox_id)
        cashbox.is_active=False
        cashbox.save()
        messages.success(request,'تم  إيقاف التنشيط بنجاح ')
        
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    
# @login_required   
# def all_transaction(request):
#     cashboxs=CashBox.objects.filter(treasurer=request.user)
#     transactions=CashTransaction.objects.filter(cashbox__in=cashboxs)

#     context={
#         'transactions':transactions
#     }
#     return render(request,'accounting/all_transaction.html',context)

from django.db.models import Sum
@login_required
def all_transaction(request):

    cashboxs = CashBox.objects.filter(treasurer=request.user)

    selected_id = request.GET.get('cashbox')

    if selected_id:
        transactions = CashTransaction.objects.filter(cashbox_id=selected_id)
    else:
        transactions = CashTransaction.objects.filter(cashbox__in=cashboxs)

    # حسابات الإيرادات والمصروفات
    total_income = transactions.aggregate(total=Sum('inbox'))['total'] or 0
    total_expenses = transactions.aggregate(total=Sum('absentminded'))['total'] or 0
    total_balance = total_income - total_expenses

    context = {
        'transactions': transactions,
        'cashboxs': cashboxs,
        'selected_id': selected_id,
        'total_income': total_income,
        'total_expenses': total_expenses,
        'total_balance': total_balance,
    }

    return render(request, 'accounting/all_transaction.html', context)

accounting/templates/accounting/add_cashbox.html
{% extends 'base.html' %}

{% block title %}
    DashBoard
{% endblock title %}
    

{% block css %}
    
{% endblock css %}



{% block body %}
<!--begin::Toolbar-->
    <div id="kt_app_toolbar" class="app-toolbar py-3 py-lg-6">
        <!--begin::Toolbar container-->
        <div id="kt_app_toolbar_container" class="app-container container-fluid d-flex flex-stack">
            <!--begin::Page title-->
            <div class="page-title d-flex flex-column justify-content-center flex-wrap me-3">
                <!--begin::Title-->
                <h1 class="page-heading d-flex text-gray-900 fw-bold fs-3 flex-column justify-content-center my-0">إضافة خزينة</h1>
                <!--end::Title-->
            
            </div>
            <!--end::Page title-->
           
        </div>
        <!--end::Toolbar container-->
    </div>
<!--end::Toolbar-->

 <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-7">

                <div class="card p-4">
                    <h3 class="text-center mb-4">إضافة خزينة جديدة</h3>

                    <form method="POST">
                        {% csrf_token %}

                        <!-- اسم الخزينة -->
                        <div class="mb-3">
                            <label class="form-label">اسم الخزينة</label>
                            <input type="text" name="name" class="form-control"  required>
                        </div>

                        <!-- النوع -->
                        <div class="mb-3">
                            <label class="form-label">نوع الخزينة</label>
                            <select name="type" class="form-select" required>
                                <option value="">اختر النوع</option>
                                <option value="CASH">نقدي</option>
                                <option value="CHEQUE">شيكات</option>
                            </select>
                        </div>

                        <!-- رئيسية / غير رئيسية -->
                        <div class="form-check form-switch mb-3">
                            <input class="form-check-input" type="checkbox" name="is_main">
                            <label class="form-check-label">هل هي الخزينة الرئيسية؟</label>
                        </div>

                        <!-- نشطة / غير نشطة -->
                        <div class="form-check form-switch mb-3">
                            <input class="form-check-input" type="checkbox" name="is_active" checked>
                            <label class="form-check-label">الخزينة نشطة</label>
                        </div>

                        <!-- أمين الخزينة -->
                        <div class="mb-3">
                            <label class="form-label">أمين الخزينة</label>
                            <select name="treasurer" class="form-select">
                                <option value="">بدون</option>
                                {% for user in users %}
                                    <option value="{{ user.id }}">{{ user.username }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <!-- التفاصيل -->
                        <div class="mb-3">
                            <label class="form-label">تفاصيل / ملاحظات</label>
                            <textarea name="details" rows="4" class="form-control" ></textarea>
                        </div>

                        <div class="text-center mt-4">
                            <button type="submit" class="btn btn-primary">حفظ الخزينة</button>
                        </div>

                    </form>

                </div>

            </div>
        </div>
    </div>
    
{% endblock body %}


   

{% block js %}
    
{% endblock js %}
    
    
    
    

accounting/templates/accounting/all_cashbox.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    الخزينة
{% endblock title %}
    

{% block css %}
    <link href="{% static 'assets/plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css"/>
{% endblock css %}



{% block body %}



<!--begin::Toolbar-->
    <div id="kt_app_toolbar" class="app-toolbar py-3 py-lg-6">
        <!--begin::Toolbar container-->
        <div id="kt_app_toolbar_container" class="app-container container-fluid d-flex flex-stack">
            <!--begin::Page title-->
            <div class="page-title d-flex flex-column justify-content-center flex-wrap me-3">
                <!--begin::Title-->
                <h1 class="page-heading d-flex text-gray-900 fw-bold fs-3 flex-column justify-content-center my-0">الخزينة</h1>
                <!--end::Title-->
            
            </div>
            <!--end::Page title-->
            <!--begin::Actions-->
            <div class="d-flex align-items-center gap-2 gap-lg-3">
                <!--begin::Secondary button-->
                <a href="{% url 'accounting:add_cashbox' %}" class="btn btn-sm fw-bold btn-secondary">إضافة خزينة</a>
                <!--end::Secondary button-->
                
            </div>
            <!--end::Actions-->
        </div>
        <!--end::Toolbar container-->
    </div>
<!--end::Toolbar-->


<form action=" {% url 'accounting:active' %}" method="post">
    {% csrf_token %}
    <div class="modal fade" tabindex="-1" id="active">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title">تنشيط</h3>

                    <!--begin::Close-->
                    <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" data-bs-dismiss="modal" aria-label="Close">
                        <i class="ki-duotone ki-cross fs-1"><span class="path1"></span><span class="path2"></span></i>
                    </div>
                    <!--end::Close-->
                </div>

                <div class="modal-body">
                    <p class="text-success">هل تريد تنشيط  هذه الخزينه ؟؟؟</p>
                    <input type="text" class="form-control" name="name" id="name">
                    <input type="hidden" name="id" id="id">
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-light" data-bs-dismiss="modal">تراجع</button>
                    <button type="submit" class="btn btn-primary">تنشيط</button>
                </div>
            </div>
        </div>
    </div>
</form>

<form action="{% url 'accounting:deactive' %}" method="post">
    {% csrf_token %}
    <div class="modal fade" tabindex="-1" id="deactive">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title">إيقاف التنشيط</h3>

                    <!--begin::Close-->
                    <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" data-bs-dismiss="modal" aria-label="Close">
                        <i class="ki-duotone ki-cross fs-1"><span class="path1"></span><span class="path2"></span></i>
                    </div>
                    <!--end::Close-->
                </div>

                <div class="modal-body">
                    <p class="text-danger">هل تريد إيقاف تنشيط  هذه الخزينه ؟؟؟</p>
                    <input type="text"  class="form-control" name="name" id="name">
                    <input type="hidden" name="id" id="id">
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-light" data-bs-dismiss="modal">تراجع</button>
                    <button type="submit" class="btn btn-primary">إيقاف التنشيط</button>
                </div>
            </div>
        </div>
    </div>
</form>

    <table id="kt_datatable_dom_positioning" class="table table-striped table-row-bordered gy-5 gs-7 border rounded">
        <thead>
            <tr class="fw-bold fs-6 text-gray-800 px-7">
                <th>التسلسل</th>
                <th>الأسم</th>
                <th>النوع</th>
                <th>رئيسى</th>
                <th>الحالة</th>
                <th>أمين الخزينة</th>
                <th> العمليات</th>
            </tr>
        </thead>
        <tbody>
        
        {% if not all_cashbox  %}
            <h1 class="text-danger">عفوا لا يوجد اى خزينة حتى الأن  !!!!</h1>
            {% else %}
               {% for item in all_cashbox %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                         
                        <td> {{item.name}}</td>
                        <td>{{item.type}}</td>
                         {% if item.is_main %}
                            <td class="text-success">رئيسى</td>
                        {% else %}
                           <td class="text-danger">غير رئيسى</td>
                        {% endif %}
                        
                        
                        {% if item.is_active %}
                            <td class="text-success">نشط</td>
                        {% else %}
                            <td class="text-danger">غير نشط</td>
                        {% endif %}
                            
                        <td>{{item.treasurer}}</td>
                        <td>
                            <div class="me-0">
                                            <button class="btn btn-sm btn-icon btn-bg-light btn-active-color-primary" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
                                                <i class="ki-solid ki-dots-horizontal fs-2x"></i>
                                            </button>
                                            <!--begin::Menu 3-->
                                            <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-800 menu-state-bg-light-primary fw-semibold w-200px py-3" data-kt-menu="true" style="">
                                                <!--begin::Heading-->
                                                <div class="menu-item px-3">
                                                    <div class="menu-content text-muted pb-2 px-3 fs-7 text-uppercase">العمليات</div>
                                                </div>
                                                <!--end::Heading-->
                                                <!--begin::Menu item-->
                                                <div class="menu-item  px-3 ">
                                                    <a class=" menu-link " href="{% url 'accounting:edit_cashbox' item.id %}" >تعديل </a>
                                                </div>
                                                <!--end::Menu item-->
                                                <!--begin::Menu item-->
                                                <div class="menu-item  px-3">
                                                     
                                                     {% if item.is_active %}
                                                        <a  href="" class = " text-danger menu-link "data-bs-target="#deactive" data-bs-toggle="modal"
                                                        data-id="{{item.id}}"
                                                        data-name="{{item.name}}" >إيقاف التنشيط</a>
                                                     {%else %}
                                                        <a data-bs-toggle="modal" href="" class = " text-success menu-link " data-bs-target="#active" 
                                                        data-id="{{item.id}}"
                                                        data-name="{{item.name}}"
                                                         >تنشيط </a>
                                                     {% endif %}
                                                        
                                                    
                                                </div>
                                                <!--end::Menu item-->
                                                    <!--begin::Menu item-->
                                                <div class="menu-item  px-3">
                                                    <a href="{% url 'accounting:transaction' item.id %}" class="menu-link px-3">الحركة</a>
                                                </div>
                                                <!--end::Menu item-->
                                            
                                            
                                            
                                            </div>
                                            <!--end::Menu 3-->
                            </div>
                        </td>
                    </tr>  
            {% endfor %}
        
             
        {% endif %}
            
         
                
         
           
        </tbody>
    </table>
        
{% endblock body %}


{% block js %}
    <script src="{% static 'assets/plugins/custom/datatables/datatables.bundle.js' %}"></script>
    <script>
        $("#kt_datatable_dom_positioning").DataTable({
	"language": {
		"lengthMenu": "Show _MENU_",
	},
	"dom":
		"<'row mb-2'" +
		"<'col-sm-6 d-flex align-items-center justify-conten-start dt-toolbar'l>" +
		"<'col-sm-6 d-flex align-items-center justify-content-end dt-toolbar'f>" +
		">" +

		"<'table-responsive'tr>" +

		"<'row'" +
		"<'col-sm-12 col-md-5 d-flex align-items-center justify-content-center justify-content-md-start'i>" +
		"<'col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end'p>" +
		">"
});
    </script>
        <script>
            $('#deactive').on('show.bs.modal', function(event) {
        var button = $(event.relatedTarget)
        var id = button.data('id')
        var name = button.data('name')
        
        var modal = $(this)
        modal.find('.modal-body #id').val(id);
        modal.find('.modal-body #name').val(name);
    
    });
    </script>

      <script>
            $('#active').on('show.bs.modal', function(event) {
        var button = $(event.relatedTarget)
        var id = button.data('id')
        var name = button.data('name')
        
        var modal = $(this)
        modal.find('.modal-body #id').val(id);
        modal.find('.modal-body #name').val(name);
    
    });
    </script>
{% endblock js %}
    
    
    
    

accounting/templates/accounting/all_transaction.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    حركة الخزينة
{% endblock title %}

{% block css %}
    <link href="{% static 'assets/plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css"/>
{% endblock css %}

{% block body %}

<!--begin::Toolbar-->

<div id="kt_app_toolbar" class="app-toolbar py-3 py-lg-6">
    <div id="kt_app_toolbar_container" class="app-container container-fluid d-flex flex-stack">

        <!--begin::Page title-->
        <div class="page-title d-flex flex-column justify-content-center flex-wrap me-3">

            <h1 class="page-heading d-flex text-gray-900 fw-bold fs-3 flex-column justify-content-center my-0">
                حركة الخزينة :   <p class="text-danger">{{ request.user }}</p>
             </h1>

        </div>
        <!--end::Page title-->

        <div class="d-flex align-items-center gap-2 gap-lg-3">
            <a href="#" class="btn btn-sm fw-bold btn-secondary" data-bs-toggle="modal" data-bs-target="#kt_modal_create_app">
                إضافة حركة
            </a>
        </div>

    </div>
</div>
<!--end::Toolbar-->

<!-- 📌 صندوق الأزرار + الملخص -->
<div class="card p-4 mb-5 shadow-sm">

    <div class=" mb-4">

        <!-- 🔵 زر إضافة إيراد -->
        <a href="#" class="btn btn-success fw-bold px-4 py-2 mb-2">
            إضافة إيراد
        </a>

        <!-- 🔴 زر إضافة مصروف -->
        <a href="#" class="btn btn-danger fw-bold px-4 py-2 mb-2">
            إضافة مصروف
        </a>

        <!-- 🟦 زر التقارير -->
        <a href="#" class="btn btn-primary fw-bold px-4 py-2 mb-2">
            التقارير
        </a>

    </div>

    <!-- 🟨 البوكسات الثلاثة -->
    <div class="row text-center">

        <!-- 🟩 رصيد الخزينة -->
        <div class="col-md-4 mb-3">
            <div class="p-3 rounded text-white fw-bold" style="background:#007bff;">
                رصيد الخزينة:
                <span class="fs-4">{{ total_balance|default:"0" }}</span>
            </div>
        </div>

        <!-- 🟦 إجمالي الإيرادات -->
        <div class="col-md-4 mb-3">
            <div class="p-3 rounded text-white fw-bold" style="background:#28a745;">
                إجمالي الإيرادات:
                <span class="fs-4">{{ total_income|default:"0" }}</span>
            </div>
        </div>

        <!-- 🟥 إجمالي المصروفات -->
        <div class="col-md-4 mb-3">
            <div class="p-3 rounded text-white fw-bold" style="background:#dc3545;">
                إجمالي المصروفات:
                <span class="fs-4">{{ total_expenses|default:"0" }}</span>
            </div>
        </div>

    </div>

</div>


<!-- 🔥 اختيار الخزينة -->
<div class="card mb-5 p-4  col-6">
    <form method="GET" class="mb-3">
        <label class="form-label fw-bold fs-5">اختر الخزينة:</label>
        <select name="cashbox" class="form-select form-select-lg" onchange="this.form.submit()">
            <option value="">-- عرض جميع الخزن --</option>

            {% for cb in cashboxs %}
                <option value="{{ cb.id }}" 
                    {% if selected_id == cb.id|stringformat:"s" %}selected{% endif %}>
                    {{ cb.name }} ({{ cb.get_type_display }})
                </option>
            {% endfor %}
        </select>
    </form>
</div>

<!-- جدول عرض الحركة -->
<table id="kt_datatable_dom_positioning" class="table table-striped table-row-bordered gy-5 gs-7 border rounded">
    <thead>
        <tr class="fw-bold fs-6 text-gray-800 px-7">
            <th>التسلسل</th>
            <th>الخزينة</th>
            <th>تاريخ الايصال</th>
            <th>رقم الايصال</th>
            <th>البيان</th>
            <th>التصنيف</th>
            <th>البند</th>
            <th>الوارد</th>
            <th>المنصرف</th>
        </tr>
    </thead>

    <tbody>
        {% for item in transactions %}
        <tr>
            <td>{{ forloop.counter }}</td>

            <td>{{ item.cashbox }}</td>

            <td>{{ item.date_transaction|date:'d-M-Y' }}</td>

            <td>{{ item.no }}</td>

            <td>
                {% if item.details %}
                    {{ item.details }}
                {% else %}
                    <span class="badge bg-danger">لا يوجد بنود</span>
                {% endif %}
            </td>

            <td>{{ item.category }}</td>

            <td>
                {% if item.inbox %}
                    <span class="badge bg-success">وارد</span>
                {% else %}
                    <span class="badge bg-danger">منصرف</span>
                {% endif %}
            </td>

            {% if item.inbox %}
                <td>{{ item.inbox }}</td>
            {% else %}
                <td>0</td>
            {% endif %}

            {% if item.absentminded %}
                <td>{{ item.absentminded }}</td>
            {% else %}
                <td>0</td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock body %}

{% block js %}
    <script src="{% static 'assets/plugins/custom/datatables/datatables.bundle.js' %}"></script>
    <script>
        $("#kt_datatable_dom_positioning").DataTable({
            "language": {"lengthMenu": "Show _MENU_"},
            "dom":
                "<'row mb-2'" +
                "<'col-sm-6 d-flex align-items-center justify-conten-start dt-toolbar'l>" +
                "<'col-sm-6 d-flex align-items-center justify-content-end dt-toolbar'f>" +
                ">" +

                "<'table-responsive'tr>" +

                "<'row'" +
                "<'col-sm-12 col-md-5 d-flex align-items-center justify-content-center justify-content-md-start'i>" +
                "<'col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end'p>" +
                ">"
        });
    </script>
{% endblock js %}