myproject/urls.py
from django.urls import path
from . import views

app_name='myproject'

urlpatterns = [
    path('<int:id>',views.myproject,name='myproject'),
    # path('create_project/<int:id>',views.create_project,name='create_project'),
    path('edit_item_',views.edit_item,name='edit_item'),
    path('project_detail/<int:id>',views.project_detail,name='project_detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from dashboard.views import index




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index),
    path('dashboard/',include('dashboard.urls')),
    path('authuser/',include('authuser.urls'),),
    
    path('tinder/',include('tinder.urls')),

    path('accounting/',include('accounting.urls')),
    path('myproject/',include('myproject.urls')),

    path('inventory/',include('inventory.urls')),
   
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tinder/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name='tinder'

urlpatterns = [

    path('all_tinder',login_required(views.all_tinder),name='all_tinder'),
    path('delete_tinder',login_required(views.delete_tinder),name='delete_tinder'),
    path('edit_tinder/<int:id>',login_required(views.edit_tinder),name='edit_tinder'),
    path('detail_tinder/<int:id>',login_required(views.detail_tinder),name='detail_tinder'),
    path('add_tinder',login_required(views.add_tinder),name='add_tinder'),
    path('save_tinder',login_required(views.save_tinder),name='save_tinder'),

    path('edit_tinder_file',login_required(views.edit_tinder_file),name='edit_tinder_file'),
    path('delete_file/<int:id>',login_required(views.delete_file),name='delete_file'),

    path('edit_item',login_required(views.edit_item),name='edit_item'),
    path('delete_item',login_required(views.delete_item),name='delete_item'),
]

tinder/models.py
from django.db import models
from utils.generate_code import generate_code
from authuser.models import User
from django.core.exceptions import ValidationError
from contact.models import Competitor,Company_by
from django.utils import timezone
import os


STATUS_TINDER=[
    ('DRAFT','DRAFT'),
    ('OPEN','OPEN'),
    ('CLOSED','CLOSED'),
    ('CANCEL','CANCEL'),
    ('AWARED','AWARED'),

]
INSURANCE_TYPE=[
    ('CASH','CASH'),
    ('CHEQUE','CHEQUE'),
    ('BANK_GUARANTEE','BANK_GUARANTEE'),
]

    # Data Base for Tinder
class Tinder(models.Model):
    code=models.CharField(max_length=75,default=generate_code)
    title=models.CharField(max_length=120)
    descriptions=models.TextField(max_length=1500)
    status=models.CharField(max_length=75,choices=STATUS_TINDER)
    
    created_at=models.DateTimeField(default=timezone.now())
    open_date=models.DateField()
    close_date=models.DateField()
    insurance_amount=models.FloatField()
    insurance_type=models.CharField(max_length=120,choices=INSURANCE_TYPE)
    awared_by=models.ForeignKey(Competitor,related_name='tinder_supplier',on_delete=models.SET_NULL,null=True,blank=True) # الشركات المنافسة
    offer_value=models.FloatField()
    created_by=models.ForeignKey(User,related_name='tinder_user',on_delete=models.SET_NULL,null=True,blank=True)
    company_by=models.ForeignKey(Company_by,related_name='tinder_supplier',on_delete=models.SET_NULL,null=True,blank=True) # الشركة المعنلة عن المناقصة


    class Meta:
        indexes =[
            models.Index(fields=['code']),
            models.Index(fields=['status'])
            
        ]

    def __str__(self):
        return str(self.title)
    
    def save(self,*args,**kwargs):
        if not self.code.startswith('tr_'):
             self.code='tr_'+self.code
        if self.close_date <= self.open_date:
             raise ValidationError('sorry this date not valid')
        
         # ✅ 3) إذا كانت المناقصة مغلقة أو مرساة يجب أن يكون لها فائز
        if self.status in ['closed', 'awared'] and not self.awared_by:
            raise ValidationError('❌ لا يمكن حفظ مناقصة مغلقة أو مرساة بدون تحديد الشركة الفائزة.')
        
        super().save(*args,**kwargs)


def tender_file_upload_path(instance, filename):
    # نحاول نستخدم كود المناقصة لو موجود
    if instance.tinder and instance.tinder.code:
        return f'files_tinder/Documents/{instance.tinder.code}/{filename}'
    return f'files_tinder/Documents/unknown/{filename}'


class TinderFiles(models.Model):
    tinder = models.ForeignKey(Tinder, related_name='filestinder', on_delete=models.CASCADE)
    files = models.FileField(upload_to=tender_file_upload_path)
    title = models.CharField(max_length=120)



    def save(self,*args,**kwargs):   # فى حالة تعديل الملف ورفع ملف جديد يحذف الملف القديم من media
        if self.pk:
            try:
                old_instance = TinderFiles.objects.get(pk=self.pk)
                if old_instance.files and self.files and old_instance.files != self.files:
                    if os.path.isfile(old_instance.files.path):
                        os.remove(old_instance.files.path)  # Delete old file

            except TinderFiles.DoesNotExist:
                pass

        super().save(*args, **kwargs)

    
    
    def delete(self, *args, **kwargs):
        # Delete the file from the storage before deleting the model instance
        if self.files and os.path.isfile(self.files.path):
            os.remove(self.files.path)
        super().delete(*args, **kwargs)



    def __str__(self):
        return self.title
    


class TindetItem(models.Model):
     tinder=models.ForeignKey(Tinder,related_name='item_tinder',on_delete=models.CASCADE)
     item=models.CharField(max_length=120)
     quantity=models.FloatField()
     code=models.CharField(max_length=25,null=True,blank=True)
     supply_price=models.FloatField(null=True,blank=True)
     tinder_price=models.FloatField(null=True,blank=True)
     unit=models.CharField(max_length=25,default='piece')
     statment=models.TextField(max_length=120)
     total=models.FloatField(default=0)

     def __str__(self):
          return self.item
     
     def save(self,*args,**kwargs):
          if self.code:
            if not self.code.startswith('it_'):
                self.code='IT_'+self.code

          if self.quantity and self.supply_price:
            if self.supply_price == 0:
                self.supply_price = 1
            self.total = self.quantity * self.supply_price
          super().save(*args,**kwargs)

tinder/views.py
from django.shortcuts import render,redirect
from .models import Tinder,TinderFiles,TindetItem
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from contact.models import Company_by,Competitor,Category
from authuser.models import User
from django.http import HttpResponseRedirect


@login_required
def all_tinder(request):
    tinders=Tinder.objects.all()

    context={
        'tinders':tinders
    }
    return render(request,'tinder/all_tinder.html',context)

@login_required
def delete_tinder(request):
   
    if request.method =='POST':
        tinder_id=request.POST.get('id')
        tinder=Tinder.objects.get(id=tinder_id)
        tinder.delete()
        messages.success(request,f'You are delete {tinder.title} successfully')
        return redirect('tinder:all_tinder')
    
@login_required   
def edit_tinder(request,id):
    tinder=Tinder.objects.get(id=id)
    awared_by=Company_by.objects.all()
    competitor=Competitor.objects.all()
    users=User.objects.all()
    status_choices = Tinder._meta.get_field('status').choices  # ✅ هكذا نحصل على choices
    insurancetype = Tinder._meta.get_field('insurance_type').choices

    tinder_file=TinderFiles.objects.filter(tinder=tinder)
    tinder_item=TindetItem.objects.filter(tinder=tinder)

    if request.method =='POST':
        title=request.POST.get('title')
        descriptions=request.POST.get('descriptions')
        open_date=request.POST.get('open_date')
        close_date=request.POST.get('close_date')
        insurance_amount=request.POST.get('insurance_amount')
        insurance_type=request.POST.get('insurance_type')
        offer_value=request.POST.get('offer_value')
        company_by_id=request.POST.get('company_by')
        awared_by_id=request.POST.get('awared_byy')
        status=request.POST.get('status')
       
        
        

        tinder.title=title
        tinder.descriptions=descriptions
        tinder.created_by=request.user

        if close_date > open_date:
            tinder.open_date = open_date
            tinder.close_date = close_date

        tinder.insurance_amount = insurance_amount
        tinder.insurance_type = insurance_type
        tinder.offer_value = offer_value
        tinder.company_by_id = company_by_id or None
        if awared_by_id:
            tinder.awared_by_id = awared_by_id or None

        tinder.status=status
        
      
        tinder.save()

        
        # ⚡ نلف على كل العناصر اللي فيها file_title
         # ⚡ نلف على كل العناصر اللي فيها file_title
        i = 0
        while True:
            title_key = f'files_list[{i}][file_title]'
            file_key = f'files_list[{i}][file_upload]'

            # توقف لو مفيش حتى عنوان (يعني مفيش عنصر)
            if title_key not in request.POST:
                break

            file_title = request.POST.get(title_key)
            file_obj = request.FILES.get(file_key)


               # شرط PDF
            if file_obj and not file_obj.name.lower().endswith('.pdf'):
                messages.error(request, "❌ الملف يجب أن يكون PDF فقط.")
                return redirect(request.META.get('HTTP_REFERER', '/'))

            # ⚡ احفظ فقط لو فيه عنوان + ملف
            if file_title and file_obj:
                TinderFiles.objects.create(
                    tinder=tinder,
                    title=file_title,
                    files=file_obj
                )

            i += 1

    ii = 0
    while True:
        item_key = f'items_list[{ii}][item]'
        quantity_key = f'items_list[{ii}][quantity]'
        suplyprice_key = f'items_list[{ii}][supply_price]'
        tinderprice_key = f'items_list[{ii}][tinder_price]'
        unit_key = f'items_list[{ii}][unit]'
        code_key = f'items_list[{ii}][code]'
        statment_key = f'items_list[{ii}][statment]'

        # توقف لو مفيش البند (يعني مفيش عنصر)
        if item_key not in request.POST:
            break

        item_title = request.POST.get(item_key)
        quantity = request.POST.get(quantity_key)
        supply_price = request.POST.get(suplyprice_key) or None
        tinder_price = request.POST.get(tinderprice_key) or None
       
        tinder_unint = request.POST.get(unit_key) 
        tinder_code = request.POST.get(code_key)
        tinder_statment = request.POST.get(statment_key)

        # ⚡ احفظ فقط لو البند مكتوب
        if item_title:
            TindetItem.objects.create(
                tinder=tinder,
                item=item_title,
                quantity=quantity,
                supply_price=supply_price,
                tinder_price=tinder_price,
                unit=tinder_unint,
                code=tinder_code,
                statment=tinder_statment
            )

        ii += 1
        
        
        messages.success(request,'تم الحفظ بنجاح')
        return redirect('tinder:all_tinder')

    context={
        'tinder':tinder,
        'awared_by':awared_by,
        'competitor':competitor,
        
        'status_choices':status_choices,
        'insurancetype':insurancetype,
        'tinder_file':tinder_file,
        'tinder_item':tinder_item,

        
    }
    return render(request,'tinder/edit_tinder.html',context)
from myproject.models import Project
@login_required
def detail_tinder(request,id):
    tinder=Tinder.objects.get(id=id)
    items=TindetItem.objects.filter(tinder=tinder)
    files=TinderFiles.objects.filter(tinder=tinder)
    project1=Project.objects.filter(tinder=tinder).first()

    context={
        'tinder':tinder,
        'items':items,
        'files':files,
        'project1':project1
    }
    return render(request,'tinder/detail_tinder.html',context)

@login_required
def add_tinder(request):
    
    status_choices = Tinder._meta.get_field('status').choices
    insurancetype_choices=Tinder._meta.get_field('insurance_type').choices

    company_by=Company_by.objects.all() # الشركات المعلنة
    competitor=Competitor.objects.all() # الشركات المنافسة

    category=Category.objects.all()


    context={
        'status_choices':status_choices,
        'insurancetype_choices':insurancetype_choices,
        'company_by':company_by,
        'competitor':competitor,
        'category':category,
    }
    return render(request,'tinder/add_tinder.html',context)

#



@login_required
def save_tinder(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        descriptions = request.POST.get('descriptions')
        status = request.POST.get('status')
        open_date = request.POST.get('open_date')
        close_date = request.POST.get('close_date')
        insurance_amount = request.POST.get('insurance_amount')
        insurance_type = request.POST.get('insurance_type')
        offer_value = request.POST.get('offer_value')
        company_by_id = request.POST.get('company_by')
        awared_by_id = request.POST.get('awared_by')

        tinder = Tinder.objects.create(
            title=title,
            descriptions=descriptions,
            status=status,
            open_date=open_date,
            close_date=close_date,
            insurance_amount=insurance_amount,
            insurance_type=insurance_type,
            offer_value=offer_value,
            company_by_id=company_by_id,
            awared_by_id=awared_by_id,
            created_by=request.user
        )

        # 👇 نطبع البيانات الواردة للتاكيد
        print("POST KEYS:", request.POST.keys())
        print("FILES KEYS:", request.FILES.keys())

        # ⚡ نلف على كل العناصر اللي فيها file_title
        i = 0
        while True:
            title_key = f'files_list[{i}][file_title]'
            file_key = f'files_list[{i}][file_upload]'

            # توقف لو مفيش حتى عنوان (يعني مفيش عنصر)
            if title_key not in request.POST:
                break

            file_title = request.POST.get(title_key)
            file_obj = request.FILES.get(file_key)


               # شرط PDF
            if file_obj and not file_obj.name.lower().endswith('.pdf'):
                messages.error(request, "❌ الملف يجب أن يكون PDF فقط.")
                return redirect(request.META.get('HTTP_REFERER', '/'))

            # ⚡ احفظ فقط لو فيه عنوان + ملف
            if file_title and file_obj:
                TinderFiles.objects.create(
                    tinder=tinder,
                    title=file_title,
                    files=file_obj
                )

            i += 1

    ii = 0
    while True:
        item_key = f'items_list[{ii}][item]'
        quantity_key = f'items_list[{ii}][quantity]'
        suplyprice_key = f'items_list[{ii}][supply_price]'
        tinderprice_key = f'items_list[{ii}][tinder_price]'
        unit_key = f'items_list[{ii}][unit]'
        code_key = f'items_list[{ii}][code]'
        statment_key = f'items_list[{ii}][statment]'

        # توقف لو مفيش البند (يعني مفيش عنصر)
        if item_key not in request.POST:
            break

        item_title = request.POST.get(item_key)
        quantity = request.POST.get(quantity_key)
        supply_price = request.POST.get(suplyprice_key) or None
        tinder_price = request.POST.get(tinderprice_key) or None
        unit = request.POST.get(unit_key)
        code = request.POST.get(code_key)
        statment = request.POST.get(statment_key)

        # ⚡ احفظ فقط لو البند مكتوب
        if item_title:
            TindetItem.objects.create(
                tinder=tinder,
                item=item_title,
                quantity=quantity,
                supply_price=supply_price,
                tinder_price=tinder_price,
                unit=unit,
                code=code,
                statment=statment
            )

        ii += 1

        messages.success(request, '✅ تم حفظ المناقصة وجميع الملفات بنجاح')
        return redirect('tinder:all_tinder')

    return redirect('tinder:add_tinder')

@login_required
def edit_tinder_file(request):
    if request.method == 'POST':
        file_id=request.POST['id']

tinder/templates/tinder/all_tinder.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Tinders
{% endblock title %}
    

{% block css %}
    <link href="{% static 'assets/plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css"/>
{% endblock css %}



{% block body %}
<!--begin::Toolbar-->
    <div id="kt_app_toolbar" class="app-toolbar py-3 py-lg-6">
        <!--begin::Toolbar container-->
        <div id="kt_app_toolbar_container" class="app-container container-fluid d-flex flex-stack">
            <!--begin::Page title-->
            <div class="page-title d-flex flex-column justify-content-center flex-wrap me-3">
                <!--begin::Title-->
                <h1 class="page-heading d-flex text-gray-900 fw-bold fs-3 flex-column justify-content-center my-0">كل المناقصات</h1>
                <!--end::Title-->
            
            </div>
            <!--end::Page title-->
            <!--begin::Actions-->
            <div class="d-flex align-items-center gap-2 gap-lg-3">
                <!--begin::Secondary button-->
              
                <!--end::Secondary button-->
                <!--begin::Primary button-->
                <a href="{% url 'tinder:add_tinder' %}" class="btn btn-sm fw-bold btn-primary" >إضافة مناقصة</a>
                <!--end::Primary button-->
            </div>
            <!--end::Actions-->
        </div>
        <!--end::Toolbar container-->
    </div>
<!--end::Toolbar-->


<form action="{% url 'tinder:delete_tinder' %}" method="post">
    {% csrf_token %}
    <div class="modal fade" tabindex="-1" id="delete_tinder">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title text-danger">حذف مناقصة</h3>

                    <!--begin::Close-->
                    <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" data-bs-dismiss="modal" aria-label="Close">
                        <i class="ki-duotone ki-cross fs-1"><span class="path1"></span><span class="path2"></span></i>
                    </div>
                    <!--end::Close-->
                </div>

                <div class="modal-body">
                    <p class="text-danger">هل تريد حذف المناقصة ؟؟؟</p>
                        <input type="text" class="form-control"  name="name" id="name" readonly>

                        <input type="hidden" name="id" id="id">
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-light" data-bs-dismiss="modal">تراجع</button>
                    <button type="submit" class="btn btn-primary">حذف المناقصة</button>
                </div>
            </div>
        </div>
    </div>
</form>

    <table id="kt_datatable_dom_positioning" class="table table-striped table-row-bordered gy-5 gs-7 border rounded">
        <thead>
            <tr class="fw-bold fs-6 text-gray-800 px-7">
                <th>التسلسل</th>
                <th>الكود</th>
                <th>العنوان</th>
                <th>تاريخ بداية المناقصة</th>
                <th>تاريخ نهاية المناقصة</th>
                <th>الفائز بها</th>
                <th>الشركة المعلنة</th>
                <th>مبلغ التأمين</th>
                <th>نوع التأمين</th>
                <th>حالة المناقصة</th>
                <th>العمليات</th>
            </tr>
        </thead>
        <tbody>
            
            {% for object in tinders %}
                 <tr>
                <td>{{forloop.counter}}</td>
                <td>{{object.code}}</td>
                <td>{{object.title}}</td>
                <td>{{object.open_date|date:"M d, Y"}}</td>
                <td>{{object.close_date|date:"M d, Y"}}</td>
            
                {% if object.status == 'AWARED'  %}
                   <td>{{object.awared_by}}</td> 
                {% else %}
                <td>Not Company awared Now</td>
                {% endif %}
                
                
                <td>{{object.company_by}}</td>
                <td>{{object.insurance_amount}}</td>
                <td>{{object.insurance_type}}</td>

                
                {% if object.status == 'AWARED' %}
                     <td class="text-success">{{object.status}}</td>
                {% elif object.status == 'OPEN' %}

                     <td class="text-danger">{{object.status}}</td>
                {% else %}

                    <td style="color: blue;">{{object.status}}</td>


                {% endif %}
                    
                
               
                    <td>
                        <div class="me-0">
                                        <button class="btn btn-sm btn-icon btn-bg-light btn-active-color-primary" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
                                            <i class="ki-solid ki-dots-horizontal fs-2x"></i>
                                        </button>
                                        <!--begin::Menu 3-->
                                        <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-800 menu-state-bg-light-primary fw-semibold w-200px py-3" data-kt-menu="true" style="">
                                            <!--begin::Heading-->
                                            <div class="menu-item px-3">
                                                <div class="menu-content text-muted pb-2 px-3 fs-7 text-uppercase">العمليات</div>
                                            </div>
                                            <!--end::Heading-->
                                            <!--begin::Menu item-->
                                            <div class="menu-item  px-3 ">
                                                <a class=" menu-link " href="" data-bs-toggle="modal" data-bs-target="#delete_tinder"
                                                data-id="{{object.id}}"
                                                data-name="{{object.title}}"
                                                 >حذف المناقصة</a>
                                            </div>
                                            <!--end::Menu item-->
                                            
                                                <!--begin::Menu item-->
                                            <div class="menu-item  px-3">
                                                <a href="{% url 'tinder:detail_tinder' object.id %}" class="menu-link px-3">التفاصيل</a>
                                            </div>
                                            <!--end::Menu item-->

                                               <!--begin::Menu item-->
                                            <div class="menu-item  px-3">
                                                <a href="{% url 'tinder:edit_tinder' object.id %}" class="menu-link px-3">تعديل المناقصة</a>
                                            </div>
                                            <!--end::Menu item-->
                                        
                                        
                                        
                                        </div>
                                        <!--end::Menu 3-->
                        </div>
                    </td>
            </tr> 
            {% endfor %}
                
          
          
        </tbody>
    </table>
    
{% endblock body %}


{% block js %}
    <script src="{% static 'assets/plugins/custom/datatables/datatables.bundle.js' %}"></script>
    <script>
        $("#kt_datatable_dom_positioning").DataTable({
	"language": {
		"lengthMenu": "Show _MENU_",
	},
	"dom":
		"<'row mb-2'" +
		"<'col-sm-6 d-flex align-items-center justify-conten-start dt-toolbar'l>" +
		"<'col-sm-6 d-flex align-items-center justify-content-end dt-toolbar'f>" +
		">" +

		"<'table-responsive'tr>" +

		"<'row'" +
		"<'col-sm-12 col-md-5 d-flex align-items-center justify-content-center justify-content-md-start'i>" +
		"<'col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end'p>" +
		">"
});
    </script>
     <script>
            $('#delete_tinder').on('show.bs.modal', function(event) {
        var button = $(event.relatedTarget)
        var id = button.data('id')
        var name = button.data('name')
        
        var modal = $(this)
        modal.find('.modal-body #id').val(id);
        modal.find('.modal-body #name').val(name);
    
    });
    </script>

{% endblock js %}
    
    
    
    