inventory/urls.py
from django.urls import path
from . import views

app_name='inventory'

urlpatterns = [
    path('products',views.products,name='products'),
    path('add_product',views.add_product,name='add_product'),
    path('save_product',views.save_product,name='save_product'),
    path('update_product/<int:id>',views.update_product,name='update_product'),
    path('delete_product',views.delete_product,name='delete_product'),
    path('product_detail/<int:id>',views.product_detail,name='product_detail'),

    # store
    path('all_store',views.all_store,name='all_store'),
    path('add_store',views.add_store,name='add_store'),
    path('save_store',views.save_store,name='save_store'),
    path('delete_store',views.delete_store,name='delete_store'),
    path('edit_store/<int:id>',views.edit_store,name='edit_store'),
    path('detail_store/<int:id>',views.store_detail,name='detail_store'),

    #brand
    path('brands',views.brands,name='brands'),
    path('add_brand',views.add_brand,name='add_brand'),
    path('delete_brand',views.delete_brand,name='delete_brand'),
    path('edit_brand/<int:id>',views.edit_brand,name='edit_brand'),

    #mainitem
    path('mainitem',views.mainitem,name='mainitem'),
    path('add_mainitem',views.add_mainitem,name='add_mainitem'),
    path('delete_mainitem',views.delete_mainitem,name='delete_mainitem'),
    path('edit_mainitem/<int:id>',views.edit_mainitem,name='edit_mainitem'),

    # transaction
    path('transaction',views.transaction,name='transactions'),
    path('supply_permit',views.supply_permit,name='supply_permit'),
    path('purchase',views.add_purchase,name='add_purchase'),
    
    path('trans_detail/<int:id>',views.trans_detail,name='trans_detail'),
    path('save_transdetail',views.save_transdetail,name='save_transdetail'),
    
    


]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from dashboard.views import index




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index),
    path('dashboard/',include('dashboard.urls')),
    path('authuser/',include('authuser.urls'),),
    
    path('tinder/',include('tinder.urls')),

    path('accounting/',include('accounting.urls')),
    path('myproject/',include('myproject.urls')),

    path('inventory/',include('inventory.urls')),
   
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tinder/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name='tinder'

urlpatterns = [

    path('all_tinder',login_required(views.all_tinder),name='all_tinder'),
    path('delete_tinder',login_required(views.delete_tinder),name='delete_tinder'),
    path('edit_tinder/<int:id>',login_required(views.edit_tinder),name='edit_tinder'),
    path('detail_tinder/<int:id>',login_required(views.detail_tinder),name='detail_tinder'),
    path('add_tinder',login_required(views.add_tinder),name='add_tinder'),
    path('save_tinder',login_required(views.save_tinder),name='save_tinder'),

    path('edit_tinder_file',login_required(views.edit_tinder_file),name='edit_tinder_file'),
    path('delete_file/<int:id>',login_required(views.delete_file),name='delete_file'),

    path('edit_item',login_required(views.edit_item),name='edit_item'),
    path('delete_item',login_required(views.delete_item),name='delete_item'),
]

inventory/views.py
from django.shortcuts import render,redirect
from .models import Product,Brand,MainItem,Store,Transaction,TranSItem
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from settings.models import Location
from authuser.models import User
from contact.models import Supplier



@login_required
def products(request):
    products=Product.objects.all().order_by('-id')
    context={
        'products':products
    }
    return render(request,'inventory/products.html',context)


@login_required
def add_product(request):
    brands=Brand.objects.all()
    mainitems=MainItem.objects.all()
    context={
        'brands':brands,
        'mainitems':mainitems
    }
    return render(request,'inventory/add_product.html',context)


@login_required
def save_product(request):
    if request.method == 'POST':
        name=request.POST.get('name')
        brand=request.POST.get('brand')
        mainitem=request.POST.get('mainitem')
        supplier=request.POST.get('supplier')
        descriptions=request.POST.get('descriptions')
        image=request.POST.get('image')
        sku=request.POST.get('sku')

        Product.objects.create(
            name=name,
            brand_id=brand,
            mainitem_id=mainitem,
            supplier_id=supplier,
            descriptions=descriptions,
            image=image,
            sku=sku

        )
        messages.success(request,'تم الحفظ')
        return redirect('inventory:products')
    
@login_required   
def delete_product(request):
    if request.method =='POST':
        product_id=request.POST.get('id')
        product=Product.objects.get(id=product_id)
        product.delete()
        messages.success(request,'تم الحذف بنجاح')
        return redirect('inventory:products')


@login_required
def update_product(request,id):

   
    product=Product.objects.get(id=id)
    brands=Brand.objects.all()
    mainitems=MainItem.objects.all()
    
    if request.method =='POST':
        

        name=request.POST.get('name')
        sku=request.POST.get('sku')
        brand=request.POST.get('brand')
        mainitem=request.POST.get('mainitem')
        supplier=request.POST.get('supplier')
        image=request.FILES.get('image')
        descriptions=request.POST.get('descriptions')

        product.name=name
        product.sku=sku,
        product.brand_id=brand
        product.mainitem_id=mainitem
        product.supplier_id=supplier
        product.image=image
        product.descriptions=descriptions

        product.save()
        messages.success(request,'تم التعديل بنجاح')
        return redirect('inventory:products')
    context={
        'product':product,
        'brands':brands,
        'mainitems':mainitems
    }
    return render(request,'inventory/update_product.html',context)

@login_required
def product_detail(request,id):
    product=Product.objects.get(id=id)
    context={
        'product':product
    }
    return render(request,'inventory/product_detail.html',context)



    
# functions for Store App

@login_required
def all_store(request):
    stores=Store.objects.all()
    context={
        'stores':stores
    }
    return render(request,'inventory/stores.html',context)
@login_required
def add_store(request):
    locations=Location.objects.all()
    users=User.objects.all()

    context={
        'locations':locations,
        'users':users
        
    }
    return render(request,'inventory/add_store.html',context)

@login_required
def save_store(request):
    if request.method == 'POST':
        name=request.POST.get('name')
        location= request.POST.get('location')
        manager=request.POST.get('manager')
        notes=request.POST.get('notes')

        Store.objects.create(
            name=name,
            location_id=location,
            manager_id=manager,
            notes=notes
        )
        messages.success(request,'تم الحفظ بنجاح')
        return redirect('inventory:all_store')
    
@login_required
def delete_store(request):
    if request.method =='POST':
        store_id=request.POST.get('id')
        store=Store.objects.get(id=store_id)
        store.delete()
        messages.success(request,'تم الحذف بنجاح')
        return redirect('inventory:all_store')
    
    
@login_required
def edit_store(request,id):

    store=Store.objects.get(id=id)
    locations=Location.objects.all()
    users=User.objects.all()

    if request.method == 'POST':
        name=request.POST.get('name')
        location=request.POST.get('location')
        manager=request.POST.get('manager')
        notes=request.POST.get('notes')

        store.name=name
        store.location_id=location
        store.manager_id=manager
        store.notes=notes

        store.save()
        messages.success(request,'تم التعديل بنجاح')
        return redirect('inventory:all_store')
        

    context={
        'store':store,
        'locations':locations,
        'users':users
    }
    return render(request,'inventory/edit_store.html',context)

@login_required
def store_detail(request,id):
    store=Store.objects.get(id=id)
    context={
        'store':store
    }
    return render(request,'inventory/detail_store.html',context)

# brands functions
@login_required
def brands(request):
    brands=Brand.objects.all()
    context={
        'brands':brands
    }
    return render(request,'inventory/brands.html',context)

@login_required
def add_brand(request):
    if request.method =='POST':
        name=request.POST.get('name')
        notes=request.POST.get('notes')
        Brand.objects.create(
            name=name,
            notes=notes
        )
        messages.success(request,'تم إضافة البراند بنجاح')
        return redirect('inventory:brands')
    return render(request,'inventory/add_brand.html',{})

@login_required
def delete_brand(request):
    if request.method == 'POST':
        brand_id=request.POST.get('id')
        brand=Brand.objects.get(id=brand_id)
        brand.delete()
        messages.success(request,' تم الحذف بنجاح')
        return redirect('inventory:brands')
    
@login_required
def edit_brand(request,id):
    brand=Brand.objects.get(id=id)
    if request.method =='POST':
        name=request.POST.get('name')
        notes=request.POST.get('notes')
        
        brand.name=name
        brand.notes=notes

        brand.save()
        messages.success(request,'تم التعديل بنجاح')
        return redirect('inventory:brands')
    context={
        'brand':brand
    }
    return render(request,'inventory/edit_brand.html',context)


# mainitem function


@login_required
def mainitem(request):
    mainitem=MainItem.objects.all()
    context={
        'mainitem':mainitem
    }
    return render(request,'inventory/mainitem.html',context)

@login_required
def add_mainitem(request):
    if request.method =='POST':
        name=request.POST.get('name')
        notes=request.POST.get('notes')
        MainItem.objects.create(
            name=name,
            notes=notes
        )
        messages.success(request,'تم إضافة البراند بنجاح')
        return redirect('inventory:mainitem')
    return render(request,'inventory/add_mainitem.html',{})

@login_required
def delete_mainitem(request):
    if request.method == 'POST':
        mainitem_id=request.POST.get('id')
        mainitem=MainItem.objects.get(id=mainitem_id)
        mainitem.delete()
        messages.success(request,' تم الحذف بنجاح')
        return redirect('inventory:mainitem')
    
@login_required
def edit_mainitem(request,id):
    mainitem=MainItem.objects.get(id=id)
    if request.method =='POST':
        name=request.POST.get('name')
        notes=request.POST.get('notes')
        
        mainitem.name=name
        mainitem.notes=notes

        mainitem.save()
        messages.success(request,'تم التعديل بنجاح')
        return redirect('inventory:mainitem')
    context={
        'mainitem':mainitem
    }
    return render(request,'inventory/edit_mainitem.html',context)

@login_required
def transaction(request):
    manager=request.user
    transactions=Transaction.objects.filter(store__manager=manager)
   


    context={
        'transactions':transactions
    }
    return render(request,'inventory/transaction.html',context)



@login_required
def supply_permit(request):
    suppliers=Supplier.objects.all()
    products=Product.objects.all()
    if request.method == 'POST':
        code=request.POST.get('code')
        reset_no=request.POST.get('no')
        date=request.POST.get('date')
        supplier=request.POST.get('supplier')

        transaction=Transaction.objects.create(
            store=Store.objects.get(manager=request.user),
            code=code,
            reset_no=reset_no,
            type='IN',
            date=date,
            supplier_id=supplier
        )
        messages.success(request,'تم الحفظ بنجاح')
        return redirect('inventory:trans_detail',transaction.id )
    
    context={
        'suppliers':suppliers,
        'products':products
    }

    
    return render(request,'inventory/supply_permit.html',context)


 

def trans_detail(request,id):
    transaction=Transaction.objects.get(id=id)
    suppliers=Supplier.objects.all()
    products=Product.objects.all()
    transitems=TranSItem.objects.filter(transaction=transaction)

    
    total = sum(item.total for item in transitems)

    
    context={
        'transaction':transaction,
        'suppliers':suppliers,
        'products':products,
        'transitems':transitems,
        'total':total
        
    }
    
   
    return render(request,'inventory/trans_detail.html',context)

def save_transdetail(request):
     if request.method =='POST':
        transaction_id=request.POST.get('id')
        transaction=Transaction.objects.get(id=transaction_id)
        product=request.POST.get('product')
        price=request.POST.get('price')
        quantity=request.POST.get('quantity')
        TranSItem.objects.create(
            transaction=transaction,

inventory/templates/inventory/brands.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
   كل البراندات
{% endblock title %}
    

{% block css %}
    <link href="{% static 'assets/plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css"/>
{% endblock css %}



{% block body %}
<!--begin::Toolbar-->
    <div id="kt_app_toolbar" class="app-toolbar py-3 py-lg-6">
        <!--begin::Toolbar container-->
        <div id="kt_app_toolbar_container" class="app-container container-fluid d-flex flex-stack">
            <!--begin::Page title-->
            <div class="page-title d-flex flex-column justify-content-center flex-wrap me-3">
                <!--begin::Title-->
                <h1 class="page-heading d-flex text-gray-900 fw-bold fs-3 flex-column justify-content-center my-0">البراندات</h1>
                <!--end::Title-->
            
            </div>
            <!--end::Page title-->
            <!--begin::Actions-->
            <div class="d-flex align-items-center gap-2 gap-lg-3">
                <!--begin::Secondary button-->
                <a href="#" class="btn btn-sm fw-bold btn-secondary" data-bs-toggle="modal" data-bs-target="#kt_modal_create_app">Rollover</a>
                <!--end::Secondary button-->
                <!--begin::Primary button-->
                <a href="{% url 'inventory:add_brand' %}" class="btn btn-sm fw-bold btn-primary" >إضافة براند</a>
                <!--end::Primary button-->
            </div>
            <!--end::Actions-->
        </div>
        <!--end::Toolbar container-->
    </div>
<!--end::Toolbar-->

<form action="{% url 'inventory:delete_brand' %}" method="post">
    {% csrf_token %}

    <div class="modal fade" tabindex="-1" id="delete_brand">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title">حذف براند</h3>

                    <!--begin::Close-->
                    <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" data-bs-dismiss="modal" aria-label="Close">
                        <i class="ki-duotone ki-cross fs-1"><span class="path1"></span><span class="path2"></span></i>
                    </div>
                    <!--end::Close-->
                </div>

                <div class="modal-body">
                    <p>هل تريد حذف هذا البراند ؟؟؟</p>
                    <input type="text" name="name" id="name" class="form-control">
                    <input type="hidden" name="id" id="id" class="form-control">
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-light" data-bs-dismiss="modal">تراجع</button>
                    <button type="submit" class="btn btn-primary">حذف البراند</button>
                </div>
            </div>
        </div>
    </div>
</form>

    <table id="kt_datatable_dom_positioning" class="table table-striped table-row-bordered gy-5 gs-7 border rounded">
        <thead>
            <tr class="fw-bold fs-6 text-gray-800 px-7">
                <th>التسلسل</th>
                <th>الأسم</th>
                <th>الكود</th>
                <th>Action</th>
               
            </tr>
        </thead>
        <tbody>
        
        {% for object in brands %}
             <tr>
                <td>{{forloop.counter}}</td>
                <td>{{object.name}}</td>
                <td>{{object.code}}</td>
                
                <td>
                    <a href="{% url 'inventory:edit_brand' object.id %}" class="btn btn-primary"  >تعديل</a>
            
                    
                    <a href="#" class="btn btn-danger"  data-bs-toggle="modal" data-bs-target="#delete_brand"
                    data-id="{{object.id}}"
                    data-name="{{object.name}}"
                    >حذف</a>
                </td>
            </tr>
        {% endfor %}
            
           
            
        </tbody>
    </table>
    
{% endblock body %}


{% block js %}
    <script src="{% static 'assets/plugins/custom/datatables/datatables.bundle.js' %}"></script>
    <script>
            $("#kt_datatable_dom_positioning").DataTable({
        "language": {
            "lengthMenu": "Show _MENU_",
        },
        "dom":
            "<'row mb-2'" +
            "<'col-sm-6 d-flex align-items-center justify-conten-start dt-toolbar'l>" +
            "<'col-sm-6 d-flex align-items-center justify-content-end dt-toolbar'f>" +
            ">" +

            "<'table-responsive'tr>" +

            "<'row'" +
            "<'col-sm-12 col-md-5 d-flex align-items-center justify-content-center justify-content-md-start'i>" +
            "<'col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end'p>" +
            ">"
    });
    </script>
    <script>
            $('#delete_brand').on('show.bs.modal', function(event) {
            var button = $(event.relatedTarget)
            var id = button.data('id')
            var name = button.data('name')
            
            var modal = $(this)
            modal.find('.modal-body #id').val(id);
            modal.find('.modal-body #name').val(name);
        
        });
    </script>
{% endblock js %}
    
    
    
    

inventory/templates/inventory/mainitem.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
   كل البراندات
{% endblock title %}
    

{% block css %}
    <link href="{% static 'assets/plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css"/>
{% endblock css %}



{% block body %}
<!--begin::Toolbar-->
    <div id="kt_app_toolbar" class="app-toolbar py-3 py-lg-6">
        <!--begin::Toolbar container-->
        <div id="kt_app_toolbar_container" class="app-container container-fluid d-flex flex-stack">
            <!--begin::Page title-->
            <div class="page-title d-flex flex-column justify-content-center flex-wrap me-3">
                <!--begin::Title-->
                <h1 class="page-heading d-flex text-gray-900 fw-bold fs-3 flex-column justify-content-center my-0">البند الرئيسى</h1>
                <!--end::Title-->
            
            </div>
            <!--end::Page title-->
            <!--begin::Actions-->
            <div class="d-flex align-items-center gap-2 gap-lg-3">
                <!--begin::Secondary button-->
                <a href="#" class="btn btn-sm fw-bold btn-secondary" data-bs-toggle="modal" data-bs-target="#kt_modal_create_app">Rollover</a>
                <!--end::Secondary button-->
                <!--begin::Primary button-->
                <a href="{% url 'inventory:add_brand' %}" class="btn btn-sm fw-bold btn-primary" >إضافة البند الرئيسى</a>
                <!--end::Primary button-->
            </div>
            <!--end::Actions-->
        </div>
        <!--end::Toolbar container-->
    </div>
<!--end::Toolbar-->

<form action="{% url 'inventory:delete_mainitem' %}" method="post">
    {% csrf_token %}

    <div class="modal fade" tabindex="-1" id="delete_brand">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title">حذف البند الرئيسى</h3>

                    <!--begin::Close-->
                    <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" data-bs-dismiss="modal" aria-label="Close">
                        <i class="ki-duotone ki-cross fs-1"><span class="path1"></span><span class="path2"></span></i>
                    </div>
                    <!--end::Close-->
                </div>

                <div class="modal-body">
                    <p>هل تريد حذف هذا البند الرئيسى ؟؟؟</p>
                    <input type="text" name="name" id="name" class="form-control">
                    <input type="hidden" name="id" id="id" class="form-control">
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-light" data-bs-dismiss="modal">تراجع</button>
                    <button type="submit" class="btn btn-primary">حذف البند الرئيسى</button>
                </div>
            </div>
        </div>
    </div>
</form>

    <table id="kt_datatable_dom_positioning" class="table table-striped table-row-bordered gy-5 gs-7 border rounded">
        <thead>
            <tr class="fw-bold fs-6 text-gray-800 px-7">
                <th>التسلسل</th>
                <th>الأسم</th>
                <th>الكود</th>
                <th>Action</th>
               
            </tr>
        </thead>
        <tbody>
        
        {% for object in mainitem %}
             <tr>
                <td>{{forloop.counter}}</td>
                <td>{{object.name}}</td>
                <td>{{object.code}}</td>
                
                   <td>
                  <a href="{% url 'inventory:edit_mainitem' object.id %}" class="btn btn-primary"  >تعديل</a>
         
                  
                  <a href="#" class="btn btn-danger"  data-bs-toggle="modal" data-bs-target="#delete_mainitem"
                  data-id="{{object.id}}"
                  data-name="{{object.name}}"
                   >حذف</a>
              </td>
            </tr>
        {% endfor %}
            
           
            
        </tbody>
    </table>
    
{% endblock body %}


{% block js %}
    <script src="{% static 'assets/plugins/custom/datatables/datatables.bundle.js' %}"></script>
    <script>
            $("#kt_datatable_dom_positioning").DataTable({
        "language": {
            "lengthMenu": "Show _MENU_",
        },
        "dom":
            "<'row mb-2'" +
            "<'col-sm-6 d-flex align-items-center justify-conten-start dt-toolbar'l>" +
            "<'col-sm-6 d-flex align-items-center justify-content-end dt-toolbar'f>" +
            ">" +

            "<'table-responsive'tr>" +

            "<'row'" +
            "<'col-sm-12 col-md-5 d-flex align-items-center justify-content-center justify-content-md-start'i>" +
            "<'col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end'p>" +
            ">"
    });
    </script>
    <script>
            $('#delete_mainitem').on('show.bs.modal', function(event) {
            var button = $(event.relatedTarget)
            var id = button.data('id')
            var name = button.data('name')
            
            var modal = $(this)
            modal.find('.modal-body #id').val(id);
            modal.find('.modal-body #name').val(name);
        
        });
    </script>
{% endblock js %}
    
    
    
    

inventory/templates/inventory/products.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    DashBoard
{% endblock title %}
    

{% block css %}
  <link href="{% static 'assets/plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css"/> 

{% endblock css %}



{% block body %}
<!--begin::Toolbar-->
    <div id="kt_app_toolbar" class="app-toolbar py-3 py-lg-6">
        <!--begin::Toolbar container-->
        <div id="kt_app_toolbar_container" class="app-container container-fluid d-flex flex-stack">
            <!--begin::Page title-->
            <div class="page-title d-flex flex-column justify-content-center flex-wrap me-3">
                <!--begin::Title-->
                <h1 class="page-heading d-flex text-gray-900 fw-bold fs-3 flex-column justify-content-center my-0">المنتجات</h1>
                <!--end::Title-->
            
            </div>
            <!--end::Page title-->
            <!--begin::Actions-->
            <div class="d-flex align-items-center gap-2 gap-lg-3">
              
                <!--begin::Primary button-->
                <a href="{% url 'inventory:add_product' %}" class="btn btn-sm fw-bold btn-primary" >إضافة منتج</a>
                <!--end::Primary button-->
            </div>
            <!--end::Actions-->
        </div>
        <!--end::Toolbar container-->
    </div>
<!--end::Toolbar-->

<!-- delete product modal -->
<form action="{% url 'inventory:delete_product' %}" method="post">
    {% csrf_token %}

    <div class="modal fade" tabindex="-1" id="delete_product">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title text-danger">حذف منتج </h3>

                    <!--begin::Close-->
                    <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" data-bs-dismiss="modal" aria-label="Close">
                        <i class="ki-duotone ki-cross fs-1"><span class="path1"></span><span class="path2"></span></i>
                    </div>
                    <!--end::Close-->
                </div>

                <div class="modal-body">
                    <p class="text-danger">هل تريد حذف هذا المنتج ؟؟؟</p>
                    <input type="hidden" name="id" id="id">
                    <input type="text" name="name" class="form-control" id="name">
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-light" data-bs-dismiss="modal">تراجع</button>
                    <button type="submit" class="btn btn-primary">حذف المنتج</button>
                </div>
            </div>
        </div>
    </div>
    <!-- end product modal -->
</form>





    <table id="kt_datatable_dom_positioning" style="width: 90%;" class="table table-striped table-row-bordered gy-5 gs-7 border rounded">
        
    {% if products %}
            
     
            
        <thead>
            <tr class="fw-bold fs-6 text-gray-800 px-7">
                <th>التسلسل</th>
                <th>أسم المنتج</th>
                <th>الكود</th>
                <th>الماركة</th>
                <th>الصورة</th>
                <th>البند الرئيسى</th>
                <th> Action</th>
            
                
                
                
            </tr>
        </thead>
        <tbody>
        
        {% for object in products %}
              <tr>
                <td >{{forloop.counter}}</td>
                <td>{{object.name}}</td>
                <td>{{object.code}}</td>
                <td>{{object.brand}}</td>
            
          

                       <td>
                            
                            {% if object.image %}
                            <div class="symbol symbol-70px me-5">
                                <img src="{{object.image.url}}" alt="">
                            </div>
                                
                            {% else %}
                            <div class="symbol symbol-70px me-5">
                                <img src="{% static 'assets/custom/45.jpg' %}" alt="Default Image" class="user-photo">
                            </div>
                             
                            {% endif %}
                                
                            
                
                <td>{{object.mainitem}}</td>
                
              <td>
                  <a href="{% url 'inventory:update_product' object.id %}" class="btn btn-primary"  >تعديل</a>
                  <a href="{% url 'inventory:product_detail' object.id %}" class="btn btn-warning">تفاصيل</a>
                  
                  <a href="#" class="btn btn-danger"  data-bs-toggle="modal" data-bs-target="#delete_product"
                  data-id="{{object.id}}"
                  data-name="{{object.name}}"
                   >حذف</a>
              </td>
                
            </tr>
        {% endfor %}
            
        </tbody>
    {% else %}
    <p class="text-danger">معذرة لا يوجد اى منتجات حتى الان !!!! </p>
    {% endif %}

    </table>
        
{% endblock body %}


{% block js %}
    <script src="{% static 'assets/plugins/custom/datatables/datatables.bundle.js' %}"></script>
    <script>
        $("#kt_datatable_dom_positioning").DataTable({
	"language": {
		"lengthMenu": "Show _MENU_",
	},
	"dom":
		"<'row mb-2'" +
		"<'col-sm-6 d-flex align-items-center justify-conten-start dt-toolbar'l>" +
		"<'col-sm-6 d-flex align-items-center justify-content-end dt-toolbar'f>" +
		">" +

		"<'table-responsive'tr>" +

		"<'row'" +
		"<'col-sm-12 col-md-5 d-flex align-items-center justify-content-center justify-content-md-start'i>" +
		"<'col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end'p>" +
		">"
});
    </script>

    <script>
            $('#delete_product').on('show.bs.modal', function(event) {
            var button = $(event.relatedTarget)
            var id = button.data('id')
            var name = button.data('name')
            
            var modal = $(this)
            modal.find('.modal-body #id').val(id);
            modal.find('.modal-body #name').val(name);
        
        });
    </script>
    <!-- <script>
            $('#update_product').on('show.bs.modal', function(event) {
            var button = $(event.relatedTarget)
            var id = button.data('id')
            var name = button.data('name')
            var sku = button.data('sku')
            var brand = button.data('d')
            var mainitem = button.data('mainitem')
            var supplier = button.data('supplier')
            var image = button.data('image')
            var descriptions = button.data('descriptions')
            
            var modal = $(this)
            modal.find('.modal-body #id').val(id);
            modal.find('.modal-body #name').val(name);
            modal.find('.modal-body #sku').val(sku);
            modal.find('.modal-body #brand').val(brand);
            modal.find('.modal-body #mainitem').val(mainitem);
            modal.find('.modal-body #supplier').val(supplier);
            modal.find('.modal-body #descriptions').val(descriptions);
        
        });
    </script> -->
{% endblock js %}
    
    
    
    